# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2025-07-22 12:44
from __future__ import unicode_literals

import apps.boxes.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxes', '0002_auto_20170416_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxprovider',
            name='file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/protected_media/', location='/project/protected_media'), upload_to=apps.boxes.models.user_box_upload_path),
        ),
        migrations.AlterField(
            model_name='boxupload',
            name='file',
            field=models.FileField(blank=True, max_length=255, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/protected_media/', location='/project/protected_media'), upload_to=apps.boxes.models.chunked_upload_path),
        ),
    ]
